routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\KegiatanController;
use App\Http\Controllers\Admin\KompetensiController;
use App\Http\Controllers\Admin\MahasiswaController;
use App\Http\Controllers\Admin\PengajuanController;
use App\Http\Controllers\Admin\PrestasiController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Mahasiswa\CetakSKPIController;
use App\Http\Controllers\Mahasiswa\HomeController;
use App\Http\Controllers\Mahasiswa\PengajuanKegiatanController;
use App\Http\Controllers\Mahasiswa\PengajuanKompetensiController;
use App\Http\Controllers\Mahasiswa\PengajuanPrestasiController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', [AuthController::class, 'login'])->middleware('guest')->name('login');
Route::post('/login', [AuthController::class, 'store'])->middleware('guest')->name('login.store');
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');



//mahasiswa
Route::prefix('mahasiswa')->middleware(['auth', 'role:mahasiswa'])->group(function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('/daftar-pengajuan', [HomeController::class, 'daftar_pengajuan'])->name('daftar-pengajuan');
    Route::get('/pengajuan-skpi', [HomeController::class, 'pengajuan_skpi'])->name('pengajuan-skpi');
    //pengajuan kegiatan
    Route::post('/pengajuan-kegiatan/store', [PengajuanKegiatanController::class, 'store'])->name('pengajuan-kegiatan.store');
    Route::get('/pengajuan-kegiatan/edit/{id}', [PengajuanKegiatanController::class, 'edit'])->name('pengajuan-kegiatan.edit');
    Route::patch('/pengajuan-kegiatan/update/{id}', [PengajuanKegiatanController::class, 'update'])->name('pengajuan-kegiatan.update');
    Route::delete('/pengajuan-kegiatan/destroy/{id}', [PengajuanKegiatanController::class, 'destroy'])->name('pengajuan-kegiatan.destroy');
    //pengajuan prestasi
    Route::post('/pengajuan-prestasi/store', [PengajuanPrestasiController::class, 'store'])->name('pengajuan-prestasi.store');
    Route::get('/pengajuan-prestasi/edit/{id}', [PengajuanPrestasiController::class, 'edit'])->name('pengajuan-prestasi.edit');
    Route::patch('/pengajuan-prestasi/update/{id}', [PengajuanPrestasiController::class, 'update'])->name('pengajuan-prestasi.update');
    Route::delete('/pengajuan-prestasi/destroy/{id}', [PengajuanPrestasiController::class, 'destroy'])->name('pengajuan-prestasi.destroy');
    //pengajuan kompetensi
    Route::post('/pengajuan-kompetensi/store', [PengajuanKompetensiController::class, 'store'])->name('pengajuan-kompetensi.store');
    Route::get('/pengajuan-kompetensi/edit/{id}', [PengajuanKompetensiController::class, 'edit'])->name('pengajuan-kompetensi.edit');
    Route::patch('/pengajuan-kompetensi/update/{id}', [PengajuanKompetensiController::class, 'update'])->name('pengajuan-kompetensi.update');
    Route::delete('/pengajuan-kompetensi/destroy/{id}', [PengajuanKompetensiController::class, 'destroy'])->name('pengajuan-kompetensi.destroy');
    //cetak
    Route::get('/cetak-skpi', [CetakSKPIController::class, 'index'])->name('cetak-skpi');
    Route::get('/cetak-skpi/pdf', [CetakSKPIController::class, 'pdf'])->name('cetak-skpi.pdf');
});

//admin
Route::prefix('admin')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');
    //pengajuan skpi
    Route::resource('kegiatan', KegiatanController::class);
    Route::resource('prestasi', PrestasiController::class);
    Route::resource('kompetensi', KompetensiController::class);
    //mahasiswa
    Route::resource('mahasiswa', MahasiswaController::class);
    Route::post('/mahasiswa/import', [MahasiswaController::class, 'import'])->name('mahasiswa.import');
    Route::get('/mahasiswa/{id}/cetak-skpi', [MahasiswaController::class, 'cetak_skpi'])->name('mahasiswa.cetak-skpi');

    //pengguna
    Route::resource('user', UserController::class);
});

app/Models/Mahasiswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mahasiswa extends Model
{
    use HasFactory;

    protected $table = 'mahasiswa';
    protected $fillable = [
        'user_id',
        'nama',
        'nim',
        'tempat_lahir',
        'tanggal_lahir',
        'kelas',
        'program_studi',
        'nomor_ijazah',
        'tanggal_kelulusan'
    ];
}

app/Http/Controllers/Admin/MahasiswaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Imports\MahasiswaImport;
use App\Models\Kegiatan;
use App\Models\Kompetensi;
use App\Models\Mahasiswa;
use App\Models\Prestasi;
use App\Models\User;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Facades\Excel;
use Maatwebsite\Excel\Validators\ValidationException;
use RealRashid\SweetAlert\Facades\Alert;

class MahasiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $mahasiswas = Mahasiswa::orderBy('nama', 'ASC')->get();
        return view('admin.mahasiswa.index', compact('mahasiswas'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.mahasiswa.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'nim' => 'required|unique:mahasiswa',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required|date',
            'kelas' => 'required',
            'program_studi' => 'required',
            'nomor_ijazah' => 'nullable|unique:mahasiswa',
            'tanggal_kelulusan' => 'nullable|date',
            'email' => 'required|email|unique:users'
        ]);

        $emailExists = User::where('email', $request->input('email'))->exists();
        $nimExists = Mahasiswa::where('nim', $request->input('nim'))->exists();

        try {
            if (!$emailExists && !$nimExists) {
                $user = User::create([
                    'name' => $request->input('nama'),
                    'email' => $request->input('email'),
                    'password' => bcrypt($request->input('nim')),
                ]);

                Mahasiswa::create([
                    'user_id' => $user->id,
                    'nama' => $request->input('nama'),
                    'nim' => $request->input('nim'),
                    'tempat_lahir' => $request->input('tempat_lahir'),
                    'tanggal_lahir' => $request->input('tanggal_lahir'),
                    'kelas' => $request->input('kelas'),
                    'program_studi' => $request->input('program_studi'),
                    'nomor_ijazah' => $request->input('nomor_ijazah'),
                    'tanggal_kelulusan' => $request->input('tanggal_kelulusan')
                ]);
                Alert::toast('Data mahasiswa berhasil ditambahkan!', 'success');
                return redirect()->back();
            } else {
                Alert::toast('Email atau NIM sudah ada dalam database!', 'error');
                return redirect()->back();
            }
        } catch (\Throwable $th) {
            Alert::toast($th->getMessage(), 'error');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $mahasiswa = Mahasiswa::findOrFail($id);
        //count pengajuan
        $countKegiatan = Kegiatan::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->count();
        $countPrestasi = Prestasi::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->count();
        $countKompetensi = Kompetensi::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->count();
        $count = $countKegiatan + $countPrestasi + $countKompetensi;
        //looping data pengajuan
        $kegiatans = Kegiatan::where('mahasiswa_id', $mahasiswa->id)->orderByRaw("status_validasi = 'Tervalidasi' DESC")->orderBy('created_at', 'DESC')->get();
        $prestasis = Prestasi::where('mahasiswa_id', $mahasiswa->id)->orderByRaw("status_validasi = 'Tervalidasi' DESC")->orderBy('created_at', 'DESC')->get();
        $kompetensis = Kompetensi::where('mahasiswa_id', $mahasiswa->id)->orderByRaw("status_validasi = 'Tervalidasi' DESC")->orderBy('created_at', 'DESC')->get();
        return view('admin.mahasiswa.show', \compact('mahasiswa', 'kegiatans', 'prestasis', 'kompetensis', 'count'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $mahasiswa = Mahasiswa::findOrFail($id);
        return view('admin.mahasiswa.edit', compact('mahasiswa'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $mahasiswa = Mahasiswa::findOrFail($id);
        $user = User::where('id', $mahasiswa->user_id)->first();

        $request->validate([
            'nama' => 'required',
            'nim' => 'required|unique:mahasiswa,nim,' . $mahasiswa->id,
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required|date',
            'kelas' => 'required',
            'program_studi' => 'required',
            'nomor_ijazah' => 'nullable|unique:mahasiswa,nomor_ijazah,' . $mahasiswa->id,
            'tanggal_kelulusan' => 'nullable|date',
        ]);

        try {
            $user->update([
                'name' => $request->input('nama'),
            ]);

            $mahasiswa->update([
                'nama' => $request->input('nama'),
                'nim' => $request->input('nim'),
                'tempat_lahir' => $request->input('tempat_lahir'),
                'tanggal_lahir' => $request->input('tanggal_lahir'),
                'kelas' => $request->input('kelas'),
                'program_studi' => $request->input('program_studi'),
                'nomor_ijazah' => $request->input('nomor_ijazah'),
                'tanggal_kelulusan' => $request->input('tanggal_kelulusan')
            ]);
            Alert::toast('Data mahasiswa berhasil diperbarui!', 'success');
            return redirect()->back();
        } catch (\Throwable $th) {
            Alert::toast($th->getMessage(), 'error');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $mahasiswa = Mahasiswa::findOrFail($id);
        $user = User::where('id', $mahasiswa->user_id)->first();

        $mahasiswa->delete();
        $user->delete();
        Alert::toast('Data mahasiswa berhasil dihapus!', 'success');
        return redirect()->back();
    }

    public function import(Request $request)
    {
        $request->validate([
            'file' => 'required|mimes:csv,xls,xlsx'
        ]);
        DB::beginTransaction();
        try {
            Excel::import(new MahasiswaImport, $request->file('file'));
            DB::commit();
            Alert::toast('Import data mahasiswa berhasil!', 'success');
            return redirect()->back();
        } catch (ValidationException $e) {
            DB::rollBack();
            Alert::toast($e->failures(), 'error');
            return redirect()->back();
        }
    }

    public function cetak_skpi($id)
    {
        $mahasiswa = Mahasiswa::findOrFail($id);
        $kegiatans = Kegiatan::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->get();
        $prestasis = Prestasi::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->get();
        $kompetensis = Kompetensi::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->get();
        $pdf = Pdf::loadView('admin.mahasiswa.cetak-skpi-pdf', \compact('mahasiswa', 'kegiatans', 'prestasis', 'kompetensis'))->setPaper('a4');
        return $pdf->stream();
    }
}

app/Http/Controllers/Mahasiswa/CetakSKPIController.php
<?php

namespace App\Http\Controllers\Mahasiswa;

use App\Http\Controllers\Controller;
use App\Models\Kegiatan;
use App\Models\Kompetensi;
use App\Models\Mahasiswa;
use App\Models\Prestasi;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CetakSKPIController extends Controller
{
    public function index()
    {
        $mahasiswa = Mahasiswa::where('user_id', Auth::user()->id)->first();
        return view('mahasiswa.cetak-skpi', \compact('mahasiswa'));
    }

    public function pdf()
    {
        $mahasiswa = Mahasiswa::where('user_id', Auth::user()->id)->first();
        $kegiatans = Kegiatan::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->get();
        $prestasis = Prestasi::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->get();
        $kompetensis = Kompetensi::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->get();
        $pdf = Pdf::loadView('mahasiswa.cetak-skpi-pdf', \compact('mahasiswa', 'kegiatans', 'prestasis', 'kompetensis'))->setPaper('a4');
        return $pdf->stream();
    }
}

app/Http/Controllers/Mahasiswa/HomeController.php
<?php

namespace App\Http\Controllers\Mahasiswa;

use App\Http\Controllers\Controller;
use App\Models\Kegiatan;
use App\Models\Kompetensi;
use App\Models\Mahasiswa;
use App\Models\Prestasi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

class HomeController extends Controller
{
    public function index()
    {
        return view('mahasiswa.home');
    }

    public function daftar_pengajuan()
    {
        $mahasiswa = Mahasiswa::where('user_id', Auth::user()->id)->first();
        //count pengajuan
        $countKegiatan = Kegiatan::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->count();
        $countPrestasi = Prestasi::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->count();
        $countKompetensi = Kompetensi::where('mahasiswa_id', $mahasiswa->id)->where('status_validasi', 'Tervalidasi')->count();
        $count = $countKegiatan + $countPrestasi + $countKompetensi;
        //looping data pengajuan
        $kegiatans = Kegiatan::where('mahasiswa_id', $mahasiswa->id)->orderByRaw("status_validasi = 'Tervalidasi' DESC")->orderBy('created_at', 'DESC')->get();
        $prestasis = Prestasi::where('mahasiswa_id', $mahasiswa->id)->orderByRaw("status_validasi = 'Tervalidasi' DESC")->orderBy('created_at', 'DESC')->get();
        $kompetensis = Kompetensi::where('mahasiswa_id', $mahasiswa->id)->orderByRaw("status_validasi = 'Tervalidasi' DESC")->orderBy('created_at', 'DESC')->get();
        return view('mahasiswa.daftar-pengajuan', \compact('mahasiswa', 'kegiatans', 'prestasis', 'kompetensis', 'count'));
    }

    public function pengajuan_skpi()
    {
        return view('mahasiswa.pengajuan-skpi');
    }

    public function store_pengajuan_kegiatan(Request $request)
    {
        $mahasiswa = Mahasiswa::where('user_id', Auth::user()->id)->first();
        $request->validate([
            'judul' => 'required',
            'tingkat' => 'required',
            'partisipasi' => 'required',
            'penyelenggara' => 'required',
            'tahun' => 'required',
            'file' => 'required|mimes:jpg,jpeg,png,pdf|max:1024'
        ]);

        $data = $request->all();
        $data['mahasiswa_id'] = $mahasiswa->id;
        $data['status_pengajuan'] = 'Pengajuan Baru';
        $data['status_validasi'] = 'Menunggu Validasi';
        try {
            if ($request->hasFile('file')) {
                $file = $request->file('file');
                $fileName = time() . '_' . $file->getClientOriginalName();
                $filePath = $file->storeAs('mahasiswa/upload/kegiatan', $fileName);
                $data['file'] = $filePath;
            }
            //\dd($data);
            Kegiatan::create($data);
            Alert::toast('Data kegiatan berhasil diajukan!', 'success');
            return redirect()->back();
        } catch (\Throwable $th) {
            Alert::toast('Something wrong!', 'error');
            return redirect()->back();
        }
    }
}

resources/views/admin/mahasiswa/create.blade.php
<x-app title="Add Mahasiswa">
    <div class="page-heading">
        <h3>Mahasiswa</h3>
    </div>
    <div class="page-content">
        <section class="section">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-titl">Add Mahasiswa</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('mahasiswa.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Nama Lengkap</label>
                                    <input type="text" name="nama" class="form-control @error('nama')
                                        is-invalid
                                    @enderror" value="{{ old('nama') }}" required>
                                    @error('nama')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="">NIM</label>
                                    <input type="text" name="nim" class="form-control @error('nim')
                                        is-invalid
                                    @enderror" value="{{ old('nim') }}" required>
                                    @error('nim')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="">Tempat Lahir</label>
                                    <input type="text" name="tempat_lahir" class="form-control @error('tempat_lahir')
                                        is-invalid
                                    @enderror" value="{{ old('tempat_lahir') }}" required>
                                    @error('tempat_lahir')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="">Tanggal Lahir</label>
                                    <input type="date" name="tanggal_lahir" class="form-control @error('tanggal_lahir')
                                        is-invalid
                                    @enderror" required>
                                    @error('tanggal_lahir')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="">Kelas</label>
                                    <select name="kelas" class="form-control @error('kelas')
                                            is-invalid
                                        @enderror" required>
                                        <option value="">-- Pilih --</option>
                                        <option value="Pagi" {{ old('kelas')=='Pagi' ? 'selected' : '' }}>Pagi
                                        </option>
                                        <option value="Sore" {{ old('kelas')=='Sore' ? 'selected' : '' }}>Sore
                                        </option>
                                        <option value="Weekend" {{ old('kelas')=='Weekend' ? 'selected' : '' }}>
                                            Weekend
                                        </option>
                                    </select>
                                    @error('kelas')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Program Studi</label>
                                    <select name="program_studi" class="form-control @error('program_studi')
                                            is-invalid
                                        @enderror" required>
                                        <option value="">-- Pilih --</option>
                                        <option value="S1 - Akuntansi" {{ old('program_studi')=='S1 - Akuntansi'
                                            ? 'selected' : '' }}>S1 -
                                            Akuntansi</option>
                                        <option value="S1 - Manajemen" {{ old('program_studi')=='S1 - Manajemen'
                                            ? 'selected' : '' }}>S1 -
                                            Manajemen</option>
                                    </select>
                                    @error('program_studi')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="">Nomor Ijazah</label>
                                    <input type="text" name="nomor_ijazah" class="form-control @error('nomor_ijazah')
                                        is-invalid
                                    @enderror" value="{{ old('nomor_ijazah') }}">
                                    @error('nomor_ijazah')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="">Tanggal Kelulusan</label>
                                    <input type="date" name="tanggal_kelulusan" class="form-control @error('tanggal_kelulusan')
                                        is-invalid
                                    @enderror">
                                    @error('tanggal_kelulusan')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="">Email</label>
                                    <input type="text" name="email" class="form-control @error('email')
                                        is-invalid
                                    @enderror" value="{{ old('email') }}" required>
                                    @error('email')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="float-end mt-3">
                            <a href="{{ route('mahasiswa.index') }}" class="btn btn-sm btn-secondary"><i
                                    class="bi bi-arrow-left"></i> Back</a>
                            <button type="submit" class="btn btn-sm btn-primary"><i class="bi bi-check"></i>
                                Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
</x-app>

resources/views/admin/mahasiswa/index.blade.php
<x-app title="Mahasiswa">
    <div class="page-heading">
        <h3>Mahasiswa</h3>
    </div>
    <div class="page-content">
        <section class="section">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">
                        Data Mahasiswa
                    </h5>
                    <div class="float-end" style="margin-top: -35px;">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-sm btn-success" data-bs-toggle="modal"
                            data-bs-target="#importModal">
                            <i class="bi bi-file-excel"></i> Import
                        </button>
                        <a href="{{ route('mahasiswa.create') }}" class="btn btn-sm btn-primary"><i
                                class="bi bi-plus"></i>
                            Add</a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-striped" id="table1" style="font-size: 14px;">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>NIM</th>
                                <th>Nama</th>
                                <th>Kelas</th>
                                <th>Program Studi</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($mahasiswas as $mahasiswa)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    <a href="{{ route('mahasiswa.show',$mahasiswa->id) }}">{{ $mahasiswa->nim }}</a>
                                </td>
                                <td>{{ $mahasiswa->nama }}</td>
                                <td>{{ $mahasiswa->kelas }}</td>
                                <td>{{ $mahasiswa->program_studi }}</td>
                                <td>
                                    <a href="{{ route('mahasiswa.edit', $mahasiswa->id) }}"
                                        class="btn btn-sm btn-warning"><i class="bi bi-pencil"></i>
                                        Edit</a>
                                    <form action="{{ route('mahasiswa.destroy', $mahasiswa->id) }}" method="POST"
                                        class="d-inline">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-danger"
                                            onclick="return confirm('Yakin ingin menghapus data ini ?')"><i
                                                class="bi bi-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="importModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Import Data Mahasiswa</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{{ route('mahasiswa.import') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label>File <a href="{{ asset('excel/format-import-mahasiswa.xlsx') }}"
                                    style="font-size: 14px;" download> ( Format File)</a></label>
                            <input type="file" class="form-control @error('file')
                                is-invalid
                            @enderror" name="file" required>
                            @error('file')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal"><i
                                class="bi bi-x"></i> Close</button>
                        <button type="submit" class="btn btn-success btn-sm"><i class="bi bi-check"></i> Import</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app>

<link rel="stylesheet" href="{{ asset('assets/extensions/datatables.net-bs5/css/dataTables.bootstrap5.min.css') }}">
<link rel="stylesheet" crossorigin href="{{ asset('assets/compiled/css/table-datatable-jquery.css') }}">
<script src="{{ asset('assets/extensions/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('assets/extensions/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/extensions/datatables.net-bs5/js/dataTables.bootstrap5.min.js') }}"></script>
<script src="{{ asset('assets/static/js/pages/datatables.js') }}"></script>